### ISSUE TITLE
Span should implement Closeable instead of AutoCloseable.

### ISSUE THREAD

**Issue by gregor-torrence** [Nike-Inc/wingtips#64]
I would like to be able to use apache commons like this:
    IOUtils.closeQuietly(span);
or use guava like this:
    Closeables.close(span, true);

Neither is possible because Span implements AutoCloseable instead of Closeable. The naming here is confusing. Closeable extends AutoCloseable. Obviously, you can't pass the super class to a method that wants the subclass.

**Comment by nicmunroe** [comment]
@gregor-torrence This should be fixed in the newly released `0.14.2`. Give it a shot and let us know if there are any problems.

Thanks for the report!

**Comment by gregor-torrence** [comment]
Works great! Thanks for making the change.
