### ISSUE TITLE
Any plans to update this to zipkin v2 api?

### ISSUE THREAD

**Issue by bhumit** [Nike-Inc/wingtips#68]

**Comment by adriancole** [comment]
i opened https://github.com/Nike-Inc/wingtips/pull/67 in preparation, but actually it isnt needed. I will raise a PR today

**Comment by adriancole** [comment]
https://github.com/Nike-Inc/wingtips/pull/69

**Comment by bhumit** [comment]
Thank you for the quick response @adriancole! 

I had a look at the #69 Thank you for the changes!

**Comment by nicmunroe** [comment]
This was on my todo-soon list as I also have a need for Zipkin 2 JSON format export. So thank you @adriancole for jumping on it! I'll add any comments I have to the PR.

**Comment by nicmunroe** [comment]
@bhumit the new `wingtips-zipkin2*` modules have been released with Wingtips `0.15.0`. Thanks for bringing this up, and thanks Adrian for all the help!
